trigger: none

pool:
  name: 'Default'   # Usa el nombre del pool donde está tu agente

steps:
  - script: |
      echo "=== Verificando conexión SSH ==="
      ssh -T git@github.com

      echo "=== Probando clonación de repositorio ==="
      git clone git@github.com/jreb-123/k8s-lab-week1.git

      echo "=== Repositorio clonado correctamente ==="
    displayName: "Test SSH & GitHub Clone"




