trigger: none

pool:
  name: default  # tu agente Ubuntu

variables:
  SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)  # tu variable de librería

steps:
# 1️⃣ Configurar clave SSH
- script: |
    echo "=== Configurando clave SSH ==="
    mkdir -p ~/.ssh
    printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa

    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa

    ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
  displayName: 'Setup SSH key'

# 2️⃣ Probar conexión a GitHub
- script: |
    echo "=== Probando conexión a GitHub ==="
    ssh -T git@github.com || true
  displayName: 'Test GitHub SSH connection'


