trigger: none

pool:
  name: default

variables:
- group: SSH_PRIVATE_KEY   # tu variable group con SSH_PRIVATE_KEY

steps:
- script: |
    echo "=== Configurando clave SSH ==="
    mkdir -p ~/.ssh
    printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa

    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa

    ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
  displayName: 'Setup SSH key'
  env:
    SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)

- script: |
    echo "=== Probando conexión a GitHub ==="
    ssh -T git@github.com || true
  displayName: 'Test GitHub SSH connection'
  env:
    SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)



