trigger:
  branches:
    include:
      - dev

variables:
  IMAGE_NAME: 'app-week1'
  ACR_NAME: 'crlabdemoj'
  IMAGE_TAG: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1
    displayName: 'Checkout código'

  - task: Docker@2
    displayName: 'Construir imagen Docker'
    inputs:
      command: 'build'
      Dockerfile: 'charts/app/Dockerfile'
      tags: |
        $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)

  - task: Docker@2
    displayName: 'Iniciar sesión en ACR y subir imagen'
    inputs:
      command: 'push'
      tags: |
        $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)

  - task: Bash@3
    displayName: 'Actualizar values.yaml con el nuevo tag'
    inputs:
      targetType: 'inline'
      script: |
        echo "Actualizando imagen en envs/dev/values.yaml"
        sed -i "s#image: .*#image: $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)#" envs/dev/values.yaml

  - task: Bash@3
    displayName: 'Commit y push del nuevo values.yaml'
    inputs:
      targetType: 'inline'
      script: |
        git config user.email "azuredevops@local"
        git config user.name "Azure DevOps Pipeline"
        git add envs/dev/values.yaml
        git commit -m "Actualización de imagen dev a $(IMAGE_TAG)"
        git push origin dev
