# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: jrebaza01/app-week1
  tag: fb45de611ad5285b601c04ba4c31dc4b7d82bdb6
  pullPolicy: IfNotPresent
 
service:
  type: ClusterIP
  port: 80
