# nginx-argo.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.3.3
    helm:
      parameters:
        - name: service.type
          value: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
