replicaCount: 2
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: jrebaza01/myapp-consolidation
  tag: ed1516adeae2a93ff067af063538d3e0792b4495

  pullPolicy: IfNotPresent
 
service:
  type: ClusterIP
  port: 80