replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: jrebaza01/myapp-consolidation
  tag: latest

  pullPolicy: IfNotPresent
 
service:
  type: ClusterIP
  port: 80