name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-week1:${{ github.sha }}

      - name: Update image tag in values.yaml
        run: |
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|g" charts/app/values.yaml
          cat charts/app/values.yaml

      - name: Commit and push updated Helm values
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/app/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
